name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        . venv/bin/activate
        # Add your test command here
        python -m unittest discover -s tests

    - name: Run Flask app
      run: |
        . venv/bin/activate
        python app.py
      env:
        SUPABASE_DB_HOST: ${{ secrets.SUPABASE_DB_HOST }}
        SUPABASE_DB_NAME: ${{ secrets.SUPABASE_DB_NAME }}
        SUPABASE_DB_USER: ${{ secrets.SUPABASE_DB_USER }}
        SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        SUPABASE_DB_PORT: ${{ secrets.SUPABASE_DB_PORT }}
