name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Verify secrets
      env:
        SUPABASE_DB_HOST: ${{ secrets.SUPABASE_DB_HOST }}
        SUPABASE_DB_NAME: ${{ secrets.SUPABASE_DB_NAME }}
        SUPABASE_DB_USER: ${{ secrets.SUPABASE_DB_USER }}
        SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        SUPABASE_DB_PORT: ${{ secrets.SUPABASE_DB_PORT }}
      run: |
        echo "SUPABASE_DB_HOST: $SUPABASE_DB_HOST"
        echo "SUPABASE_DB_NAME: $SUPABASE_DB_NAME"
        echo "SUPABASE_DB_USER: $SUPABASE_DB_USER"
        echo "SUPABASE_DB_PASSWORD: $SUPABASE_DB_PASSWORD"
        echo "SUPABASE_DB_PORT: $SUPABASE_DB_PORT"
