name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        SUPABASE_DB_HOST: ${{ secrets.SUPABASE_DB_HOST }}
        SUPABASE_DB_NAME: ${{ secrets.SUPABASE_DB_NAME }}
        SUPABASE_DB_USER: ${{ secrets.SUPABASE_DB_USER }}
        SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        SUPABASE_DB_PORT: ${{ secrets.SUPABASE_DB_PORT }}
      run: |
        echo $SUPABASE_DB_HOST >> secrets.txt
        echo $SUPABASE_DB_NAME >> secrets.txt
        echo $SUPABASE_DB_USER >> secrets.txt
        echo $SUPABASE_DB_PASSWORD >> secrets.txt
        echo $SUPABASE_DB_PORT >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
